rm(list = ls())

library(cli)
library(lubridate)
library(reprex)
library(tidyverse)
library(geosphere)
library(reshape2)
library(moderndive)
library(skimr)
library(ggridges)
library(weathercan)
library(GGally)
library(psych)
library(raster)
library(PBSmapping)
library(rgeos)
library(knitr)
library(kableExtra)
library(grid)
library(gridExtra)
library(cowplot)

#Load Data
setwd("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Source Data/Fat Data")
Main = read_csv("Master.csv")
Con = read_csv("Connors 2004-2017.csv")
Com1 = read_csv("Comeaus 2005-2010.csv")
Com2 = read_csv("Comeaus 2017.csv")
Com3 = read_csv("Comeaus 2018.csv")
Com4 = read_csv("Comeaus 2020.csv")
Com5 = read_csv("Comeaus 2021.csv")
Scotia = read_csv("Scotia 2017-2018.csv")
Unkn = read_csv("Unknown 2007-2013.csv")

#Standardize Data
