#### biomass calculation from transects exported from Echoview into excel
#Integrations must be placed in same folder and seperated (e.g. GB and SI)

rm(list=ls())

library(dplyr)
library(geosphere)
library(sp)
library(rgdal)
library(raster)
library(adehabitatHR)
library(plotKML)


setwd('C:/Users/herri/OneDrive/Documents/Jenna/ecomod/acousticHerring/src/_Rfunctions/')
source("transects.R")


setwd('C:/Users/herri/OneDrive/Documents/Surveys/2020/Scots Bay/2020-07-11/Exports/')

file_list <- list.files(path = getwd())
transects <- data.frame()


#identify columns to keep from csv files
keep <- c("Dist_S","Dist_E", "Date_S", "Time_S", "Date_E","Time_E", "Lat_S","Lon_S","Lat_E","Lon_E", "Region_name", "Ping_S", "Ping_E", "EV_filename","Area_Backscatter_Strength", "Frequency")


#for each file in file_list, read in csv, keep specified columns, rbind to dataset to produce one dataset
for (i in 1:length(file_list)){
  temp_data <- read.csv(file_list[i])
  temp_data2 <- temp_data[keep]
  transects <- rbind(transects, temp_data2)
}

### Continue work here - trying to use my functions with the .csv generated by the script Export.R

# Use trans function
setwd('C:/Users/herri/OneDrive/Documents/Jenna/ecomod/acousticHerring/src/_Rfunctions/')
source("transects.R")



transects(transects, TS38 = -35.5, TS50 = -35.609)

TS38 <- -35.5 ###### Code directly to Length Frequences EVENTUALLY ##########
TS50 <- -35.609 ###### Code directly to Length Frequences EVENTUALLY ##########

setwd('C:/Users/herri/OneDrive/Documents/Surveys/2020/Scots Bay/2020-07-11/Exports/')



rm(temp_data,temp_data2)

transects_German <- filter(transects, Lat_S <43.67 & Lat_E < 43.67 & Lon_S < -66.259 & Lon_E < -66.259) #need to check whether this is accurate
transects_SealIsland <-  filter(transects, !Region_name %in% as.character(transects_German$Region_name))

transects_German<- rbind(transects_German, transects_SealIsland[7,])
transects_German

transects_SealIsland<-transects_SealIsland[1:6,]


#### German Bank #### 

#calculate area of survey
area_calc = function(x) {
Longitude  <-c(x$Lon_S,x$Lon_E)
Latitude  <-c(x$Lat_S, x$Lat_E)
LatLonMat <-matrix(c(Longitude,Latitude),ncol=2)
survey_coord <-SpatialPoints(LatLonMat)
crs.geo <- CRS("+proj=utm +zone=20 +datum=WGS84")

proj4string(survey_coord) <- crs.geo
is.projected(survey_coord)
summary(survey_coord)

survey_area <- mcp(survey_coord, percent = 100)
area<-survey_area$area*100000000 #Converts to km squared. originally in Hectares, but not sure why it's million too small.
return(area)
}
area<-area_calc(transects_German)

biomassCalc = function(x, area) {
  TS38 <- -35.5 ###### Code directly to Length Frequences EVENTUALLY ##########
  TS50 <- -35.609 ###### Code directly to Length Frequences EVENTUALLY ##########
  #x = transects_German
  x$areaKm = area
  
  # Analysis
  x$distance = (x$Dist_E - x$Dist_S)/1000
  x$sum_trans =sum(x$distance)
  x$Actual_Weighting = (x$distance)/(x$sum_trans)
  x$calc_actual_mean_sa = 10^(x$Area_Backscatter_Strength/10)*x$Actual_Weighting
  x$TS <- as.numeric(ifelse(grepl(38, x$Frequency), TS38, TS50))
  x$biomass_density = 10^((x$Area_Backscatter_Strength-(x$TS))/10) # same as Jenna's Transects.R script calculation
  x$density = (x$biomass_density)*(x$distance)
  x$weighted_mean_biomass_calc = (x$biomass_density) * (x$Actual_Weighting)
  x$trans_biomass = (x$weighted_mean_biomass_calc) * x$areaKm * 1000
  x$total_biomass = sum(x$trans_biomass)
  
  se <- function(x) sqrt(var(x)/length(x))
  x$se = se(x$biomass_density)
  x$standard_error_tonnes = x$se * x$areaKm * 1000
  x$standard_error_perc = x$standard_error_tonnes/x$total_biomass*100
  x$mean_biomass_density = mean(x$biomass_density)
  x$meanSa = 10*log10(sum(x$calc_actual_mean_sa))
  
  return(x)
}
transects_German

biomassCalc(transects_German,area)

#Seal Island
area<-area_calc(transects_SealIsland)
area
biomassCalc(transects_SealIsland,area)
