---
title: "Survey Factors"
output: html_document
date: "2024-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

library(rlang)
library(cli)
library(lubridate)
library(reprex)
library(tidyverse)
library(geosphere)
library(reshape2)
library(moderndive)
library(skimr)
library(ggridges)
library(weathercan)
library(GGally)
library(psych)
library(sp)
library(raster)
library(PBSmapping)
library(rgeos) # replaced by terra and sf
library(knitr)
library(kableExtra)
library(grid)
library(gridExtra)
library(cowplot)
library(readxl)
library(hms)
library(measurements)
library(ggplot2)
library(maps)
library(dplyr)
library(RColorBrewer)
library(AICcmodavg)
library(datasets)
library(terra)
library(multcompView)
library(sf)
library(zoo)
library(ggrepel)
library(tidyr)

###remove everything in environment
options(scipen = 999)

setwd("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Source Data/Survey Factors")

Survey_Factors <- read_csv(
  "C:/Users/herri/Documents/GitHub/HerringScience.github.io/Source Data/Survey Factors/surveyFactorsAll.csv"
) %>%
  mutate(
    Survey_Date = as.Date(Survey_Date),
    Julian = yday(Survey_Date)
  )

#Survey_Factors$Julian = as.POSIXlt(Survey_Factors$Survey_Date)$yday

SSBEstimates <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Main Data/SSB Estimates.csv")
Survey_Data <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Main Data/Survey Data.csv")

RollingPeakBiomassAvg <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Tracey's Folder/RollingPeakBiomassAvg.csv")
RollingPeakBiomassAvgGB <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Tracey's Folder/RollingPeakBiomassAvgGB.csv")

```
# {.tabset}

## Julian and Biomass {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBay_Turnover <- Survey_Factors %>%
  dplyr::select(
    Survey_Date,
    Ground,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit() %>%
  filter(Ground == "SB")

ggplot(
  ScotsBay_Turnover,
  aes(Julian, DFO_Estimate)
) +
  geom_point() +
  geom_smooth(span = 1) +
  labs(
    x = "Julian Day",
    y = "Survey Biomass (mt)"
  )

summary(
  aov(
    DFO_Estimate ~ Julian,
    data = ScotsBay_Turnover
  )
)

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankTurnover <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    Ground,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit()

ggplot(
  GermanBankTurnover,
  aes(Julian, DFO_Estimate)
) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    x = "Julian Day",
    y = "Survey Biomass (mt)"
  )

summary(
  lm(
    DFO_Estimate ~ Julian,
    data = GermanBankTurnover
  )
)

```

## Number of Vessels and Biomass {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

SBVesselsBiomass <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  dplyr::select(
    Survey_Date,
    No_of_Vessels,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit() %>%
  mutate(
    No_of_Vessels = factor(No_of_Vessels)
  )

boxplot(
  DFO_Estimate ~ No_of_Vessels,
  data = SBVesselsBiomass,
  xlab = "Number of Vessels",
  ylab = "Survey Biomass (mt)"
)

summary(
  aov(
    DFO_Estimate ~ No_of_Vessels,
    data = SBVesselsBiomass
  )
)

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GBVesselsBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    No_of_Vessels,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit() %>%
  mutate(
    No_of_Vessels = factor(No_of_Vessels)
  )

boxplot(
  DFO_Estimate ~ No_of_Vessels,
  data = GBVesselsBiomass,
  xlab = "Number of Vessels",
  ylab = "Survey Biomass (mt)"
)

summary(
  aov(
    DFO_Estimate ~ No_of_Vessels,
    data = GBVesselsBiomass
  )
)

```


## Tide Relative and Biomass {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBayHighTideBiomass <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Tide_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

ScotsBayHighTideBiomass$Tide_Relative <-
  as.numeric(
    ScotsBayHighTideBiomass$Tide_Relative
  )

ggplot(
  ScotsBayHighTideBiomass,
  aes(
    Tide_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(span = 1)

summary(
  aov(
    DFO_Estimate ~ Tide_Relative,
    data = ScotsBayHighTideBiomass
  )
)

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankHighTideBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Tide_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

GermanBankHighTideBiomass$Tide_Relative <-
  as.numeric(
    GermanBankHighTideBiomass$Tide_Relative
  )

ggplot(
  GermanBankHighTideBiomass,
  aes(
    Tide_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(method = "lm")

summary(
  lm(
    DFO_Estimate ~ Tide_Relative,
    data = GermanBankHighTideBiomass
  )
)

```


## Sunset Relative {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBaySunsetData <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Sunset_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

ScotsBaySunsetData$Sunset_Relative <-
  as.numeric(
    ScotsBaySunsetData$Sunset_Relative
  )

ggplot(
  ScotsBaySunsetData,
  aes(
    Sunset_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(method = "lm")

summary(
  lm(
    DFO_Estimate ~ Sunset_Relative,
    data = ScotsBaySunsetData
  )
)

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankSunsetData <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Sunset_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

GermanBankSunsetData$Sunset_Relative <-
  as.numeric(
    GermanBankSunsetData$Sunset_Relative
  )

ggplot(
  GermanBankSunsetData,
  aes(
    Sunset_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(method = "lm")

summary(
  lm(
    DFO_Estimate ~ Sunset_Relative,
    data = GermanBankSunsetData
  )
)

```


## Peak Biomass {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBayPeakBiomass <- Survey_Factors %>%
  filter(
    Ground == "SB"
  ) %>%
  filter(
    !is.na(DFO_Turnover_Adjusted),
    !is.na(Julian),
    !is.na(Year)
  ) %>%
  group_by(Year) %>%
  slice_max(
    DFO_Turnover_Adjusted,
    n = 1,
    with_ties = FALSE
  ) %>%
  ungroup()

ggplot(
  ScotsBayPeakBiomass,
  aes(
    Julian,
    DFO_Turnover_Adjusted
  )
) +
  geom_point(size = 3) +
  geom_label_repel(
    aes(label = Year)
  ) +
  labs(
    x = "Julian Day",
    y = "Peak Biomass (mt)"
  )

summary(
  lm(
    DFO_Turnover_Adjusted ~ Year,
    data = ScotsBayPeakBiomass
  )
)

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankPeakBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  group_by(Year) %>%
  slice_max(
    DFO_Turnover_Adjusted,
    n = 1,
    with_ties = FALSE
  ) %>%
  ungroup() %>%
  drop_na(
    Julian,
    DFO_Turnover_Adjusted,
    Year
  )

ggplot(
  GermanBankPeakBiomass,
  aes(
    Julian,
    DFO_Turnover_Adjusted
  )
) +
  geom_point(size = 3) +
  geom_label_repel(
    aes(label = Year)
  )

summary(
  lm(
    DFO_Turnover_Adjusted ~ Year,
    data = GermanBankPeakBiomass
  )
)

```

## Index Trend {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

aggregateSB <- Survey_Factors %>%
  filter(
    Ground == "SB"
  ) %>%
  filter(
    !is.na(DFO_Estimate)
  ) %>%
  group_by(Year) %>%
  summarise(
    Total_Biomass = sum(
      DFO_Estimate
    ),
    .groups = "drop"
  )

ggplot(
  aggregateSB,
  aes(
    Year,
    Total_Biomass
  )
) +
  geom_line() +
  geom_point()

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

aggregateGB <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  group_by(Year) %>%
  summarise(
    Total_Biomass = sum(DFO_Estimate),
    .groups = "drop"
  )

ggplot(
  aggregateGB,
  aes(
    Year,
    Total_Biomass
  )
) +
  geom_line() +
  geom_point()

```

## Three Year Rolling Average {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ThreeYearRollingBiomass <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  group_by(Year) %>%
  summarise(
    Biomass = sum(
      DFO_Turnover_Adjusted
    ),
    .groups = "drop"
  ) %>%
  mutate(
    RollingAvg = zoo::rollmean(
      Biomass,
      k = 3,
      fill = NA,
      align = "right"
    )
  )

ggplot(
  ThreeYearRollingBiomass,
  aes(
    Year,
    RollingAvg
  )
) +
  geom_line() +
  geom_point()

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ThreeYearRollingBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  group_by(Year) %>%
  summarise(
    Biomass = sum(
      DFO_Turnover_Adjusted
    ),
    .groups = "drop"
  ) %>%
  mutate(
    RollingAvg = zoo::rollmean(
      Biomass,
      k = 3,
      fill = NA,
      align = "right"
    )
  )

ggplot(
  ThreeYearRollingBiomass,
  aes(
    Year,
    RollingAvg
  )
) +
  geom_line() +
  geom_point()

```