---
title: "Survey Factors"
output: html_document
date: "2026-07-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

library(rlang)
library(cli)
library(lubridate)
library(reprex)
library(tidyverse)
library(geosphere)
library(reshape2)
library(moderndive)
library(skimr)
library(ggridges)
library(weathercan)
library(GGally)
library(psych)
library(sp)
library(raster)
library(PBSmapping)
library(rgeos) # replaced by terra and sf
library(knitr)
library(kableExtra)
library(grid)
library(gridExtra)
library(cowplot)
library(readxl)
library(hms)
library(measurements)
library(ggplot2)
library(maps)
library(dplyr)
library(RColorBrewer)
library(AICcmodavg)
library(datasets)
library(terra)
library(multcompView)
library(sf)
library(zoo)
library(ggrepel)
library(tidyr)


setwd("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Source Data/Survey Factors")

Survey_Factors <- read_csv(
  "C:/Users/herri/Documents/GitHub/HerringScience.github.io/Source Data/Survey Factors/surveyFactorsAll.csv"
) %>%
  mutate(
    Survey_Date = as.Date(Survey_Date),
    Julian = yday(Survey_Date)
  )

Survey_Factors <- Survey_Factors %>%
  drop_na(DFO_Turnover_Adjusted)

#Survey_Factors$Julian = as.POSIXlt(Survey_Factors$Survey_Date)$yday

SSBEstimates <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Main Data/SSB Estimates.csv")
Survey_Data <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Main Data/Survey Data.csv")

RollingPeakBiomassAvg <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Tracey's Folder/RollingPeakBiomassAvg.csv")
RollingPeakBiomassAvgGB <- read_csv("C:/Users/herri/Documents/GitHub/HerringScience.github.io/Tracey's Folder/RollingPeakBiomassAvgGB.csv")

# Read data
df <- read.csv("surveyFactorsAll.csv")

# Convert variables to numeric
df$DFO_Turnover_Adjusted <- as.numeric(df$DFO_Turnover_Adjusted)
df$Tide_Relative <- as.numeric(df$Tide_Relative)
df$Sunset_Relative <- as.numeric(df$Sunset_Relative)
df$Survey_Date <- as.Date(df$Survey_Date)
df$MonthNum <- as.numeric(format(df$Survey_Date, "%m"))
df$No_of_Vessels <- as.numeric(df$No_of_Vessels)

# Remove missing values
dat <- subset(df,
              !is.na(DFO_Turnover_Adjusted) &
              !is.na(Tide_Relative) &
              !is.na(Sunset_Relative) &
              !is.na(No_of_Vessels))

# Log-transform biomass
dat$logBiomass <- log10(dat$DFO_Turnover_Adjusted + 1)

# Split datasets
GB <- subset(dat, Ground == "GB")
SB <- subset(dat, Ground == "SB")

#Scots Bay Model

model_SB <- lm(logBiomass ~ Tide_Relative +
                            Sunset_Relative +
                            Julian +
                            No_of_Vessels,
               data = SB)

#German Bank Model

df$MonthNum <- as.numeric(format(df$Survey_Date, "%m"))

model_GB <- lm(logBiomass ~ Tide_Relative +
                            Sunset_Relative +
                            Julian +
                            No_of_Vessels,
               data = GB)
```
# {.tabset}

## Julian Date {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBay_Turnover <- Survey_Factors %>%
  dplyr::select(
    Survey_Date,
    Ground,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit() %>%
  filter(Ground == "SB")


ggplot(
  ScotsBay_Turnover,
  aes(Julian, DFO_Estimate)
) +
  geom_point() +
  geom_smooth(span = 1) +
  labs(
    x = "Julian Date",
    y = "Survey Biomass (mt)"
  )


cor.test(SB$DFO_Turnover_Adjusted,
         SB$Julian,
         method = "spearman")

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankTurnover <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    Ground,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit()

ggplot(
  GermanBankTurnover,
  aes(Julian, DFO_Estimate)
) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    x = "Julian Date",
    y = "Survey Biomass (mt)"
  )


cor.test(GB$DFO_Turnover_Adjusted,
         GB$Julian,
         method = "spearman")


```

## Number of Vessels{.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

SBVesselsBiomass <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  dplyr::select(
    Survey_Date,
    No_of_Vessels,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit() %>%
  mutate(
    No_of_Vessels = factor(No_of_Vessels)
  )

boxplot(
  DFO_Estimate ~ No_of_Vessels,
  data = SBVesselsBiomass,
  xlab = "Number of Vessels",
  ylab = "Survey Biomass (mt)"
)

cor.test(dat$No_of_Vessels,
         dat$Julian,
         method = "spearman")

cor.test(
  SB$DFO_Turnover_Adjusted,
  SB$No_of_Vessels,
  method = "spearman"
)

cor.test(dat$No_of_Vessels,
         dat$Julian,
         method = "spearman")

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GBVesselsBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    No_of_Vessels,
    Julian,
    DFO_Estimate
  ) %>%
  na.omit() %>%
  mutate(
    No_of_Vessels = factor(No_of_Vessels)
  )

boxplot(
  DFO_Estimate ~ No_of_Vessels,
  data = GBVesselsBiomass,
  xlab = "Number of Vessels",
  ylab = "Survey Biomass (mt)"
)

cor.test(dat$No_of_Vessels,
         dat$Julian,
         method = "spearman")

cor.test(
  GB$DFO_Turnover_Adjusted,
  GB$No_of_Vessels,
  method = "spearman"
)

```


## Tide Relative {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBayHighTideBiomass <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Tide_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

ScotsBayHighTideBiomass$Tide_Relative <-
  as.numeric(
    ScotsBayHighTideBiomass$Tide_Relative
  )


ggplot(
  ScotsBayHighTideBiomass,
  aes(
    Tide_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(span = 1)

cor.test(SB$DFO_Turnover_Adjusted,
         SB$Tide_Relative,
         method = "spearman")

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankHighTideBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Tide_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

GermanBankHighTideBiomass$Tide_Relative <-
  as.numeric(
    GermanBankHighTideBiomass$Tide_Relative
  )

ggplot(
  GermanBankHighTideBiomass,
  aes(
    Tide_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(method = "lm")

cor.test(GB$DFO_Turnover_Adjusted,
         GB$Tide_Relative,
         method = "spearman")
```


## Sunset Relative {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBaySunsetData <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Sunset_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

ScotsBaySunsetData$Sunset_Relative <-
  as.numeric(
    ScotsBaySunsetData$Sunset_Relative
  )

ggplot(
  ScotsBaySunsetData,
  aes(
    Sunset_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(method = "lm")

cor.test(SB$DFO_Turnover_Adjusted,
         SB$Sunset_Relative,
         method = "spearman")


```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankSunsetData <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  dplyr::select(
    Survey_Date,
    Year,
    Sunset_Relative,
    DFO_Estimate
  ) %>%
  na.omit()

GermanBankSunsetData$Sunset_Relative <-
  as.numeric(
    GermanBankSunsetData$Sunset_Relative
  )

ggplot(
  GermanBankSunsetData,
  aes(
    Sunset_Relative,
    DFO_Estimate
  )
) +
  geom_point() +
  geom_smooth(method = "lm")

corr_table <-cor.test(GB$DFO_Turnover_Adjusted,
         GB$Sunset_Relative,
         method = "spearman")

```


## Peak Biomass {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ScotsBayPeakBiomass <- Survey_Factors %>%
  filter(
    Ground == "SB"
  ) %>%
  filter(
    !is.na(DFO_Turnover_Adjusted),
    !is.na(Julian),
    !is.na(Year)
  ) %>%
  group_by(Year) %>%
  slice_max(
    DFO_Turnover_Adjusted,
    n = 1,
    with_ties = FALSE
  ) %>%
  ungroup()

ScotsBayPeakBiomass <- ScotsBayPeakBiomass %>%
  mutate(
    Survey_Date = as.Date(Survey_Date),
    Month = factor(format(Survey_Date, "%b"),
                   levels = month.abb)
  )

ggplot(
  ScotsBayPeakBiomass,
  aes(
    x = Julian,
    y = DFO_Turnover_Adjusted,
    color = Month
  )
) +
  geom_point(size = 3) +
  geom_label_repel(
    aes(
      label = Year,
      fill = Month
    ),
    color = "black"
  ) +
  labs(
    x = "Julian Day",
    y = "Peak Biomass (mt)",
    color = "Month",
    fill = "Month"
  ) +
    guides(
    fill = guide_legend(
      override.aes = list(label = "")
    )
  ) +
  theme_bw()


```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

GermanBankPeakBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  group_by(Year) %>%
  slice_max(
    DFO_Turnover_Adjusted,
    n = 1,
    with_ties = FALSE
  ) %>%
  ungroup() %>%
  drop_na(
    Julian,
    DFO_Turnover_Adjusted,
    Year
  )

GermanBankPeakBiomass <- GermanBankPeakBiomass %>%
  mutate(
    Survey_Date = as.Date(Survey_Date),
    Month = factor(format(Survey_Date, "%b"),
                   levels = month.abb)
  )

ggplot(
  GermanBankPeakBiomass,
  aes(
    x = Julian,
    y = DFO_Turnover_Adjusted,
    color = Month
  )
) +
  geom_point(size = 3) +
  geom_label_repel(
    aes(
      label = Year,
      fill = Month
    ),
    color = "black"
  ) +
  labs(
    x = "Julian Day",
    y = "Peak Biomass (mt)",
    color = "Month",
    fill = "Month"
  ) +
  guides(
    fill = guide_legend(
      override.aes = list(label = "")
    )
  ) +
  theme_bw()


```

## Index Trend {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

aggregateSB <- Survey_Factors %>%
  filter(
    Ground == "SB"
  ) %>%
  filter(
    !is.na(DFO_Estimate)
  ) %>%
  group_by(Year) %>%
  summarise(
    Total_Biomass = sum(
      DFO_Estimate
    ),
    .groups = "drop"
  )

ggplot(
  aggregateSB,
  aes(
    Year,
    Total_Biomass
  )
) +
  geom_line() +
  geom_point()

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

##Missing 2013 and 2015.

aggregateGB <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  group_by(Year) %>%
  summarise(
    Total_Biomass = sum(DFO_Estimate, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(
  aggregateGB,
  aes(
    Year,
    Total_Biomass
  )
) +
  geom_line() +
  geom_point()

```

## Three Year Rolling Average {.tabset}

### Scots Bay

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ThreeYearRollingBiomass <- Survey_Factors %>%
  filter(Ground == "SB") %>%
  group_by(Year) %>%
  summarise(
    Biomass = sum(
      DFO_Turnover_Adjusted
    ),
    .groups = "drop"
  ) %>%
  mutate(
    RollingAvg = zoo::rollmean(
      Biomass,
      k = 3,
      fill = NA,
      align = "right"
    )
  )

ggplot(
  ThreeYearRollingBiomass,
  aes(
    Year,
    RollingAvg
  )
) +
  geom_line() +
  geom_point()

```

### German Bank

```{r, echo=FALSE, message=FALSE, warning=FALSE}

ThreeYearRollingBiomass <- Survey_Factors %>%
  filter(Ground == "GB") %>%
  group_by(Year) %>%
  summarise(
    Biomass = sum(
      DFO_Turnover_Adjusted
    ),
    .groups = "drop"
  ) %>%
  mutate(
    RollingAvg = zoo::rollmean(
      Biomass,
      k = 3,
      fill = NA,
      align = "right"
    )
  )

ggplot(
  ThreeYearRollingBiomass,
  aes(
    Year,
    RollingAvg
  )
) +
  geom_line() +
  geom_point()

```

## Spearman Correlations {.tabset}

```{r, echo=FALSE, message=FALSE, warning=FALSE}

###### if p-value > 0.5, fail to reject the hypothesis. Therefore not significantly significant.

# # Read data
# df <- read.csv("surveyFactorsAll.csv")
# 
# # Convert variables to numeric
# df$DFO_Turnover_Adjusted <- as.numeric(df$DFO_Turnover_Adjusted)
# df$Tide_Relative <- as.numeric(df$Tide_Relative)
# df$Sunset_Relative <- as.numeric(df$Sunset_Relative)
# df$Survey_Date <- as.Date(df$Survey_Date)
# df$MonthNum <- as.numeric(format(df$Survey_Date, "%m"))
# df$No_of_Vessels <- as.numeric(df$No_of_Vessels)
# 
# # Remove missing values
# dat <- subset(df,
#               !is.na(DFO_Turnover_Adjusted) &
#               !is.na(Tide_Relative) &
#               !is.na(Sunset_Relative) &
#               !is.na(No_of_Vessels))
# 
# # Log-transform biomass
# dat$logBiomass <- log10(dat$DFO_Turnover_Adjusted + 1)
# 
# # Split datasets
# GB <- subset(dat, Ground == "GB")
# SB <- subset(dat, Ground == "SB")
# 
# #Scots Bay model
# 
# model_SB <- lm(logBiomass ~ Tide_Relative +
#                             Sunset_Relative +
#                             Julian +
#                             No_of_Vessels,
#                data = SB)

# summary(model_SB)

# Scots Bay Spearman correlation validation

# cor.test(SB$DFO_Turnover_Adjusted,
#          SB$Tide_Relative,
#          method = "spearman")
# 
# cor.test(SB$DFO_Turnover_Adjusted,
#          SB$Sunset_Relative,
#          method = "spearman")
# 
# cor.test(SB$DFO_Turnover_Adjusted,
#          SB$Julian,
#          method = "spearman")
# 
# cor.test(
#   SB$DFO_Turnover_Adjusted,
#   SB$No_of_Vessels,
#   method = "spearman"
# )
# 
# cor.test(dat$No_of_Vessels,
#          dat$Julian,
#          method = "spearman")

#German Bank model 
# df$MonthNum <- as.numeric(format(df$Survey_Date, "%m"))
# 
# model_GB <- lm(logBiomass ~ Tide_Relative +
#                             Sunset_Relative +
#                             Julian +
#                             No_of_Vessels,
#                data = GB)

#summary(model_GB)

##German Bank Spearman correlations 
# 
# cor.test(GB$DFO_Turnover_Adjusted,
#          GB$Tide_Relative,
#          method = "spearman")
# 
# cor.test(GB$DFO_Turnover_Adjusted,
#          GB$Sunset_Relative,
#          method = "spearman")
# 
# cor.test(GB$DFO_Turnover_Adjusted,
#          GB$Julian,
#          method = "spearman")
# 
# cor.test(
#   GB$DFO_Turnover_Adjusted,
#   GB$No_of_Vessels,
#   method = "spearman"
# )
corr_table <- data.frame(
  Location = c(
    "German Bank","German Bank","German Bank","German Bank",
    "Scots Bay","Scots Bay","Scots Bay","Scots Bay"
  ),
  Variable = c(
    "Tide Relative",
    "Sunset Relative",
    "Julian Day",
    "No. of Vessels",
    "Tide Relative",
    "Sunset Relative",
    "Julian Day",
    "No. of Vessels"
  ),
  Rho = c(
    -0.162,
    -0.177,
    -0.367,
     0.287,
     0.077,
     0.183,
    -0.448,
     0.185
  ),
  P_Value = c(
    0.0833,
    0.0589,
    0.0000536,
    0.001889,
    0.3429,
    0.0237,
    0.00000000649,
    0.0222
  )
)

corr_table$Significance <- ifelse(
  corr_table$P_Value < 0.001, "***",
  ifelse(corr_table$P_Value < 0.01, "**",
         ifelse(corr_table$P_Value < 0.05, "*", "ns"))
)

ggplot(corr_table,
       aes(x = Variable,
           y = Rho,
           fill = Location)) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(aes(label = round(Rho, 2)),
            position = position_dodge(width = 0.9),
            vjust = -0.3) +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  labs(
    title = "Spearman Correlations with Biomass",
    y = "Spearman's rho",
    x = ""
  ) +
  theme_bw()

```